
"@context":

ontologies:

## DUO

  - id: duo
    preferredPrefix: DUO
    title: Data use ontology
    uri: http://purl.obolibrary.org/obo/duo.owl
    description: "DUO is an ontology which represent data use conditions."
    homepage: https://github.com/EBISPOT/DUO
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
      - http://purl.obolibrary.org/obo/RO_0002202
    base_uri:
      - http://purl.obolibrary.org/obo/DUO_
    reasoner: EL
    oboSlims: false
    ontology_purl: file:///opt/ols/duo.owl

